name: "z17CX"
title: null
description: "System administrator and web developer."
image: ""
lang: "ru-RU"

defaults:
  - scope:
      path: ""
    values:
      image: ""

author:
  name: "z17CX"
  email: "mail@z17.cx"
  github: "z17cx"
  twitter: "z17cx"

twitter:
  username: "z17cx"
  card: summary

social:
  name: "z17cx"
  links:
    - https://github.com/z17cx

webmaster_verifications:
  google: "JP8xL1s_oeKkyIi0gxXsewBiBGiTqyoRwnKDZ3zC_uI"
  yandex: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
